IR_BLOCK( 0, NONE,                      {})
IR_BLOCK( 1, START,                     {})
IR_BLOCK( 2, END,                       {})
IR_BLOCK( 3, BEGIN_FUNC_DEF,            {})
IR_BLOCK( 4, END_FUNC_DEF,              {})
IR_BLOCK( 5, CALL_FUNC,                 {})
IR_BLOCK( 6, RET,                       {})
IR_BLOCK( 7, INIT_MEM_FOR_GLOBALS,      {})
IR_BLOCK( 8, COUNT_ARR_ELEM_ADDR_CONST, {})
IR_BLOCK( 9, ARR_ELEM_ADDR_ADD_INDEX,   {})
IR_BLOCK(10, MOV,                       {})
IR_BLOCK(11, SWAP,                      {})
IR_BLOCK(12, STORE_CMP_RES,             {})
IR_BLOCK(13, SET_FLAGS_CMP_WITH_ZERO,   {})
IR_BLOCK(14, MATH_OPER,                 {})
IR_BLOCK(15, JUMP,                      {})
IR_BLOCK(16, READ_DOUBLE,               {})
IR_BLOCK(17, PRINT_DOUBLE,              {})
